test:
  adapter: postgresql
  encoding: unicode
  database: bookmark_manager_test
  pool: 2
  username: tomdoh


production:
  adapter: postgresql
  encoding: unicode
  database: bookmark_manager
  pool: 2
  username: tomdoh
